Add GIF loader.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/gui/trunk@18339 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3589,6 +3589,72 @@ echo "$as_me: error: libpng not found." >&2;}
   fi
 fi
 
+
+echo "$as_me:$LINENO: checking for DGifOpen in -lungif" >&5
+echo $ECHO_N "checking for DGifOpen in -lungif... $ECHO_C" >&6
+if test "${ac_cv_lib_ungif_DGifOpen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lungif  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char DGifOpen ();
+int
+main ()
+{
+DGifOpen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ungif_DGifOpen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ungif_DGifOpen=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ungif_DGifOpen" >&5
+echo "${ECHO_T}$ac_cv_lib_ungif_DGifOpen" >&6
+if test $ac_cv_lib_ungif_DGifOpen = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBUNGIF 1
+_ACEOF
+
+  LIBS="-lungif $LIBS"
+
+fi
+
+
+
 #--------------------------------------------------------------------
 # NSSound
 #--------------------------------------------------------------------
