Check for recent version of audiofile
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/gui/trunk@14223 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3178,6 +3178,70 @@ ADDITIONAL_DEPENDS="$GRAPHIC_LIBS"
 #--------------------------------------------------------------------
 # NSSound
 #--------------------------------------------------------------------
+audio_ok=no
+BUILD_GSND=
+echo "$as_me:$LINENO: checking for afGetVirtualFrameSize in -laudiofile" >&5
+echo $ECHO_N "checking for afGetVirtualFrameSize in -laudiofile... $ECHO_C" >&6
+if test "${ac_cv_lib_audiofile_afGetVirtualFrameSize+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-laudiofile  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char afGetVirtualFrameSize ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+afGetVirtualFrameSize ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_audiofile_afGetVirtualFrameSize=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_audiofile_afGetVirtualFrameSize=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_audiofile_afGetVirtualFrameSize" >&5
+echo "${ECHO_T}$ac_cv_lib_audiofile_afGetVirtualFrameSize" >&6
+if test $ac_cv_lib_audiofile_afGetVirtualFrameSize = yes; then
+  audio_ok=yes
+else
+  audio_ok=no
+fi
+
+if test $audio_ok = yes; then
 
 for ac_header in audiofile.h
 do
@@ -3292,64 +3356,6 @@ fi
 
 done
 
-audio_ok=no
-BUILD_GSND=
-echo "$as_me:$LINENO: checking for main in -laudiofile" >&5
-echo $ECHO_N "checking for main in -laudiofile... $ECHO_C" >&6
-if test "${ac_cv_lib_audiofile_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-laudiofile  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_audiofile_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_audiofile_main=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_audiofile_main" >&5
-echo "${ECHO_T}$ac_cv_lib_audiofile_main" >&6
-if test $ac_cv_lib_audiofile_main = yes; then
-  audio_ok=yes
-else
-  audio_ok=no
-fi
-
-if test $audio_ok = yes; then
   ADDITIONAL_DEPENDS="$ADDITIONAL_DEPENDS -laudiofile"
   BUILD_GSND=gsnd
 fi
