Add a new character picker panel. It's accessible via a button in the font panel.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/gui/trunk@33470 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -609,6 +609,9 @@ GSCUPS_CFLAGS
 have_cups
 BUILD_SPEECH
 BUILD_SOUND
+HAVE_ICU
+ICU_LIBS
+ICU_CONFIG
 IMAGEMAGICK_LIBS
 IMAGEMAGICK_CFLAGS
 PKG_CONFIG_LIBDIR
@@ -691,6 +694,7 @@ enable_png
 enable_ungif
 enable_libgif
 enable_imagemagick
+enable_icu
 enable_aspell
 enable_sound
 enable_speech
@@ -1334,6 +1338,7 @@ Optional Features:
   --disable-ungif         Disable libungif-based GIF support
   --enable-libgif         Enable libgif-based GIF support
   --disable-imagemagick        Disable ImageMagick support
+  --disable-icu		Disable International Components for Unicode
   --disable-aspell        Disable aspell for spellchecker
   --disable-sound          Disable sound
   --disable-speech          Disable speech server
@@ -5629,6 +5634,136 @@ $as_echo "#define HAVE_IMAGEMAGICK 1" >>confdefs.h
 fi
 
 fi
+
+#--------------------------------------------------------------------
+# Check for International Components for Unicode
+# See DEPENDENCIES POLICY at the start of thsi file.
+#--------------------------------------------------------------------
+HAVE_ICU=0
+# Check whether --enable-icu was given.
+if test "${enable_icu+set}" = set; then :
+  enableval=$enable_icu;
+else
+  enable_icu=yes
+fi
+
+
+if test $enable_icu = yes; then
+
+  ok=no
+
+  if test -z "$ICU_CONFIG"; then
+    # Extract the first word of "icu-config", so it can be a program name with args.
+set dummy icu-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_path_ICU_CONFIG+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $ICU_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ICU_CONFIG="$ICU_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ICU_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_ICU_CONFIG" && ac_cv_path_ICU_CONFIG="no"
+  ;;
+esac
+fi
+ICU_CONFIG=$ac_cv_path_ICU_CONFIG
+if test -n "$ICU_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ICU_CONFIG" >&5
+$as_echo "$ICU_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+  fi
+
+  if test "$ICU_CONFIG" = "no" ; then
+    echo "Could not find the icu-config script."
+    echo "Please ensure that it is in your path."
+    echo "See http://site.icu-project.org/ for help."
+  else
+    ICU_VERSION=`$ICU_CONFIG --version`
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for ICU >= 4.0" >&5
+$as_echo_n "checking for ICU >= 4.0... " >&6; }
+      found=`expr $ICU_VERSION \>= 4.0`
+      if test "$found" = "1" ; then
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	ok=yes
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking ICU_LIBS" >&5
+$as_echo_n "checking ICU_LIBS... " >&6; }
+	ICU_LIBS=`$ICU_CONFIG --ldflags-libsonly`
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ICU_LIBS" >&5
+$as_echo "$ICU_LIBS" >&6; }
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking ICU_LDFLAGS" >&5
+$as_echo_n "checking ICU_LDFLAGS... " >&6; }
+	ICU_LDFLAGS=`$ICU_CONFIG --ldflags-searchpath`
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ICU_LDFLAGS" >&5
+$as_echo "$ICU_LDFLAGS" >&6; }
+      else
+	ICU_LIBS=""
+	ICU_LDFLAGS=""
+	## Either perform custom action or print error message
+
+      fi
+
+
+  fi
+
+  if test $ok = yes; then
+    have_icu=yes
+  else
+    have_icu=no
+  fi
+
+  if test "$have_icu" = "yes"; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+    for ac_header in unicode/uchar.h unicode/ustring.h
+do :
+  as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
+ac_fn_c_check_header_mongrel "$LINENO" "$ac_header" "$as_ac_Header" "$ac_includes_default"
+if eval test \"x\$"$as_ac_Header"\" = x"yes"; then :
+  cat >>confdefs.h <<_ACEOF
+#define `$as_echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+    LIBS="$LIBS $ICU_LIBS"
+    LDFLAGS="$LDFLAGS $ICU_LDFLAGS"
+    LDIR_FLAGS="$LDIR_FLAGS $ICU_LDFLAGS"
+    HAVE_ICU=1
+  else
+    { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: The International Components for Unicode (ICU) development headers and libraries do not appear to be available on this system." >&5
+$as_echo "$as_me: WARNING: The International Components for Unicode (ICU) development headers and libraries do not appear to be available on this system." >&2;}
+  fi
+fi
+
 
 #--------------------------------------------------------------------
 # Check for the spelling lib, for the built-in spell checker...
